### ISSUE TITLE
Use template-literal instead of EJS

### ISSUE THREAD

**Issue by Drulac** [tx4x/control-freak#2]
[Template Literal](https://github.com/Drulac/template-literal) is fastest, smallest and simplest template engine, because it use JS's literal template feature.

It's  55 times faster than EJS, and it also use less CPU and RAM ressources, so it may be a good idea to use it instead of EJS 😀

**Comment by tx4x** [comment]
thanks, control-freak is currently being rewritten and evtl. we will make use of it. we use EJS for a very brief and single moment, happens per client once, i don't think there is anything to gain
